### ISSUE TITLE
can't run dask job in the latest prefect version 

### ISSUE THREAD

**Issue by cometta** [PrefectHQ/prefect#3226]
i'm using version 0.13.4, when i run dask in k8s, i get below error . It was working in version ~v0.12

> kubectl logs -f prefect-dask-job-8da65936-dc90-4876-9e8c-bf8dbcb73409-2w9vt  --namespace prefect-workers
```
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.191.109:37630
distributed.scheduler - INFO -   dashboard at:                     :8787
[2020-08-27 03:10:27] INFO - prefect.CloudFlowRunner | Beginning Flow run for 'dask-example'
distributed.scheduler - INFO - Receive client connection: Client-dc0e940a-e812-11ea-8008-d27edf85cf7e
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://192.168.191.111:39388', name: 0, memory: 0, processing: 2>
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.191.111:39388
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-worker-e06218b0-e812-11ea-800b-4a93ce4abc77
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-worker-e0629442-e812-11ea-800b-4a93ce4abc77
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Scheduler for 4.80s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 448, in wait_for
    await _cancel_and_wait(fut, loop=loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 509, in _cancel_and_wait
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 448, in wait_for
    await _cancel_and_wait(fut, loop=loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 509, in _cancel_and_wait
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.core - INFO - Event loop was unresponsive in Scheduler for 5.61s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.scheduler - INFO - Remove worker <Worker 'tcp://192.168.191.111:39388', name: 0, memory: 2, processing: 7>
distributed.core - INFO - Removing comms to tcp://192.168.191.111:39388
distributed.scheduler - INFO - Lost all workers
distributed.core - INFO - Event loop was unresponsive in Scheduler for 5.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.core - INFO - Event loop was unresponsive in Scheduler for 3.51s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - INFO - Connection closed before handshake completed
```

> kubectl logs -f dask-root-38673076-2rl4bc  --namespace prefect-workers

```
/usr/local/lib/python3.7/site-packages/distributed/cli/dask_worker.py:277: UserWarning: The --bokeh/--no-bokeh flag has been renamed to --dashboard/--no-dashboard.
  "The --bokeh/--no-bokeh flag has been renamed to --dashboard/--no-dashboard. "
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.191.111:44686'
distributed.worker - INFO -       Start worker at: tcp://192.168.191.111:39388
distributed.worker - INFO -          Listening to: tcp://192.168.191.111:39388
distributed.worker - INFO -          dashboard at:      192.168.191.111:46430
distributed.worker - INFO - Waiting to connect to: tcp://192.168.191.109:37630
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    4.00 GB
distributed.worker - INFO -       Local Directory: /dask-worker-space/dask-worker-space/worker-l_dbxv1b
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to: tcp://192.168.191.109:37630
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
[2020-08-27 03:10:36] INFO - prefect.CloudTaskRunner | Task 'Constant[range]': Starting task run...
[2020-08-27 03:10:36] INFO - prefect.CloudTaskRunner | Task 'Constant[range]': Starting task run...
[2020-08-27 03:10:37] INFO - prefect.CloudTaskRunner | Task 'Constant[range]': finished task run for task with final state: 'Success'
[2020-08-27 03:10:37] INFO - prefect.CloudTaskRunner | Task 'Constant[range]': finished task run for task with final state: 'Success'
[2020-08-27 03:10:39] INFO - prefect.CloudTaskRunner | Task 'dec': Starting task run...
[2020-08-27 03:10:39] INFO - prefect.CloudTaskRunner | Task 'dec': finished task run for task with final state: 'Mapped'
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.worker - INFO - Stopping worker at tcp://192.168.191.111:39388
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.nanny - INFO - Worker closed
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 289, in _
    write = await asyncio.wait_for(comm.write(local_info), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 289, in _
    write = await asyncio.wait_for(comm.write(local_info), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 289, in _
    write = await asyncio.wait_for(comm.write(local_info), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 289, in _
    write = await asyncio.wait_for(comm.write(local_info), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /usr/local/lib/python3.7/site-packages/distributed/comm/core.py:279> exception=CommClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 289, in _
    write = await asyncio.wait_for(comm.write(local_info), 1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 295, in _
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://192.168.191.111:44686'
distributed.nanny - WARNING - Worker process still alive after 1 seconds, killing
distributed.dask_worker - INFO - End worker
distributed.process - INFO - reaping stray process <SpawnProcess(Dask Worker process (from Nanny), started daemon)>
```

error in prefect ui console
```
Unexpected error: AttributeError("'NoneType' object has no attribute 'is_finished'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 359, in check_upstream_finished
    if not all(s.is_finished() for s in all_states):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 359, in <genexpr>
    if not all(s.is_finished() for s in all_states):
AttributeError: 'NoneType' object has no attribute 'is_finished'

Unexpected error: AttributeError("'NoneType' object has no attribute 'is_skipped'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 394, in check_upstream_skipped
    if self.task.skip_on_upstream_skip and any(s.is_skipped() for s in all_states):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 394, in <genexpr>
    if self.task.skip_on_upstream_skip and any(s.is_skipped() for s in all_states):
AttributeError: 'NoneType' object has no attribute 'is_skipped'
```

**Comment by jcrist** [comment]
Hi @cometta, I'm unable to reproduce. Can you provide steps to reproduce the issue?

From the logs it looks like you might have mismatched versions of distributed between your pods (the prefect job pod and the dask worker/scheduler pods specifically), which is causing some connection issues. You might need to update/check the images you're using to ensure the versions of dask & distributed match.

**Comment by cometta** [comment]
@jcrist any advice how to check this, because i use the prefect command deploy the agent in k8s. i do not use any special yaml file.

**Comment by jcrist** [comment]
Can you share the environment + storage configuration you're using?

**Comment by cometta** [comment]
@jcrist environment is =kubernetes , storage, for prefect agent, i don't think it use any pv or pvc .

**Comment by jcrist** [comment]
Sorry, by environment + storage configuration I meant what configuration have you set on `flow.environment` and `flow.storage`? There are many ways to run prefect and dask on kubernetes, just knowing that you're using kubernetes isn't enough. See https://docs.prefect.io/orchestration/execution/overview.html.

**Comment by cometta** [comment]
this exmple work on version ~ 0.12 ; i think the pod always pull the latest image , thus i was force to delete them and reinstall with latest prefect.
 
```
Flow("dask-example", environment=DaskKubernetesEnvironment(min_workers=3, max_workers=3, worker_spec_file="worker_spec.yaml"),
    storage=Docker(
        registry_url="docker_hub_account", image_name="dash-example"
    )) 
```

**Comment by jcrist** [comment]
Hmmm, with that configuration the workers and scheduler should share the same image. There might be a bug though. If you look at a running job, you should be able to check the images match at runtime. Something like this should do it.

```
kubectl get pod -n YOUR_NAMESPACE -l prefect.io/flow_run_id=YOUR_FLOW_RUN_ID -o=custom-columns='DATA:spec.containers[*].image'
```

If they all are using the same image and you're still having issues then we'll have to investigate further.

**Comment by cometta** [comment]
@jcrist the output for 3 dask workers 

```
kubectl get pod -n MY_NAMESPACE -l prefect.io/flow_run_id=cb3402ba-2ec0-4636-9939-07a793942ffd -o=custom-columns='DATA:spec.containers[*].image'
DATA
DOCKER_ACC/dash-example:2020-08-29t07-16-53-126789-00-00
DOCKER_ACC/dash-example:2020-08-29t07-16-53-126789-00-00
DOCKER_ACC/dash-example:2020-08-29t07-16-53-126789-00-00
DOCKER_ACC/dash-example:2020-08-29t07-16-53-126789-00-00
```

in the prefect ui, i can see error
```
State Message:
Trigger was "all_successful" but some of the upstream tasks failed.

Failed to retrieve task results: 'NoneType' object has no attribute 'load_result'
Unexpected error: AttributeError("'NoneType' object has no attribute 'is_skipped'")

Unexpected error: AttributeError("'NoneType' object has no attribute 'is_finished'")
```

**Comment by cometta** [comment]
apologies, my mistake, for 1.5, there is changes for docker-compose-build.yml mount volume /fate/python/fate_flow which previously mount to /fate/fate_flow . issue resolved. Thank you
