### PR TITLE
Fix AnyIO 4.10.0 and Apprise Compatibility Issues

### PR DESCRIPTION
**Pull request by jnissin**
# Fix AnyIO 4.10.0 and Apprise Compatibility Issues

## Summary

Fixes multiple compatibility issues that arose when upgrading AnyIO to 4.10.0, including apprise breaking changes, TaskGroup lifecycle issues, SQLite concurrency problems, and test environment issues. There was [a previous dependabot PR](https://github.com/PrefectHQ/prefect/pull/18644) already open about this, but the tests were failing.

## Problem 1: Apprise Compatibility Issues

Upgrading anyio triggered an apprise update to 1.9.4, which introduced breaking changes:

1. **Data structure change**: `apprise.NOTIFY_TYPES` changed from `tuple` to `frozenset`, breaking our `+=` operation
2. **URL format change**: Opsgenie URLs changed format, causing test failures

**Error**: `TypeError: unsupported operand type(s) for +=: 'frozenset' and 'tuple'`

**Solution**: Updated notification block initialization to handle both data structures using set operations, and updated test expectations to match the new URL format.

## Problem 2: AnyIO TaskGroup Lifecycle Issues

The `Runner` and `TaskServer` classes were reusing `anyio.TaskGroup` instances across multiple start/stop cycles. AnyIO's `TaskGroup.__aexit__` deletes the `_exceptions` attribute in its `finally` block, causing `AttributeError: 'TaskGroup' object has no attribute '_exceptions'` on subsequent uses.

**Solution**: Reinitialize the `_exceptions` attribute in `__aenter__` methods instead of creating new TaskGroup instances. This preserves object identity for safer compatibility with existing code that might hold references to these TaskGroups.

## Problem 3: SQLite Concurrency Issues

The notification service test `test_service_sends_many_notifications_and_clears_queue` was failing due to SQLite database lock errors when processing many notifications rapidly.

**Error**: `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked`

**Root Cause**: SQLite's concurrency limitations were hit when processing 200 notifications in rapid succession. Database lock errors invalidate the entire SQLAlchemy session, preventing proper cleanup.

**Solution**: Added service-level retry logic with exponential backoff (5 retries with 50ms, 100ms, 200ms, 400ms delays) to handle transient SQLite lock errors gracefully.

### NumPy Reload Warnings
NumPy reload warnings were being treated as errors due to `pytest.approx()` importing NumPy multiple times during test runs.

**Solution**: Added warning filter in `setup.cfg` to ignore non-critical NumPy reload warnings.

### Schema Validation Test Failures
`PrefectBaseModel` checks `PREFECT_TEST_MODE` environment variable to determine validation strictness, but it wasn't being set during test runs.

**Solution**: Explicitly set `PREFECT_TEST_MODE=1` in pytest configuration to ensure proper validation behavior during tests.

## Files Changed

- `requirements-client.txt`: Updated anyio version constraint to `< 4.10.0`
- `src/prefect/blocks/notifications.py`: Fixed apprise NOTIFY_TYPES compatibility
- `tests/blocks/test_notifications.py`: Updated Opsgenie URL format expectations
- `src/prefect/runner/runner.py`: Updated TaskGroup lifecycle management
- `src/prefect/task_server.py`: Updated TaskGroup lifecycle management
- `src/prefect/server/services/flow_run_notifications.py`: Added service-level retry logic for SQLite database locks
- `setup.cfg`: Added NumPy reload warning filter

## Testing

All AnyIO 4.10.0 compatibility issues have been resolved. The previously failing tests now pass when run with:

```
PREFECT_TEST_MODE=1 python -m pytest tests
```

**Note**: The full test suite shows 2 unrelated flaky test failures that are not caused by our changes:
- `tests/test_logging.py::TestAPILogWorker::test_logs_are_sent_immediately_when_stopped` (timing-sensitive test)
- `tests/workers/test_base_worker.py::test_job_configuration_from_template_overrides_with_block` (test isolation warning)

Both tests pass when run individually, confirming they are pre-existing issues unrelated to AnyIO compatibility.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @jnissin - thanks for opening this PR. i think we should reduce the scope of it to make it easier to confidently merge it

1. i think you identified a real issue that we already fixed in 3.x: see https://github.com/PrefectHQ/prefect/pull/18697
2. this is a bound we have intentionally not moved in 2.x, but the tests appear to look fine for you here so I think we'd be willing to include this if everything looks good
3. sqlite locking is an issue at scale across the board, i dont think this PR should attempt to fix that unless you have an isolated case you're solving for. i'd recommend removing related changes here
4. its not clear why this is necessary / desirable
> Added warning filter in setup.cfg to ignore non-critical NumPy reload warnings.

i'll note that we try to minimize changes to 2.x at this point as it nears an EoL state

**Comment by jnissin** [comment]
hi @zzstoatzz !

Sorry, for going overboard I just tried to make the full test suite pass. My bad. I'll remove the changes to:

* flow_run_notifications.py
* setup.cfg

Regarding why this is desirable: This is probably quite specific to our use case, but we are in a situation currently where we are using prefect 2.x and upgrading it would involve quite a lot of work. We lately introduced a change that had a dependency that updated `anyio` above the supported version range (through `google-genai` package) so I decided to take a look at how difficult would it be to support it in the 2.x branch.

**Comment by jnissin** [comment]
Removed changes to `setup.cfg` and `flow_run_notifications.py` this should decrease the scope quite a bit. I also updated the PR description accordingly. Thanks for the feedback 👍 .

**Comment by jnissin** [comment]
I also took a look at the referenced PR and implemented the 3.x branch strategy to `NOTIFY_TYPES` handling in `notifications.py`

File: src/prefect/runner/runner.py [hunk 1]
```diff
@@ -1165,6 +1165,13 @@ async def __aenter__(self):
         self._client = get_client()
         self._tmp_dir.mkdir(parents=True)
         await self._client.__aenter__()
+
+        # Re-initialize both TaskGroups' _exceptions attributes each time to avoid reuse
+        # issues with anyio >4.4.0. The __aexit__ method of the TaskGroup deletes the
+        # _exceptions attribute and this causes issues.
+        self._runs_task_group._exceptions = []
+        self._loops_task_group._exceptions = []
```
Comment (desertaxle) [inline src/prefect/runner/runner.py]: Instead of accessing a privatish variable here, you can solve this issue by deferring the creation of the task groups until `__aenter__` is called. That way, a fresh task group is created each time the `Runner` context is entered. That's how we handle it in 3.x, but that change was never back-ported.

Comment (jnissin) [reply src/prefect/runner/runner.py]: Agreed, the same applies to `task_server.py` I suppose. That was my original approach, but I was uncertain if something is relying on the TaskGroup objects to remain the same and felt like this approach was less risky since I don't know the codebase.

Thanks for the comments! I'll change these to create new task groups instead.

Comment (jnissin) [reply src/prefect/runner/runner.py]: Done

File: requirements-client.txt [hunk 2]
```diff
@@ -1,4 +1,4 @@
-anyio >= 4.4.0, < 4.6.1
+anyio >= 4.4.0, < 4.10.1
```
Comment (desertaxle) [inline requirements-client.txt]: I think we can bump the upper limit for `anyio` so that we don't cause issues similar to the ones you're seeing in a couple of months.
```suggestion
anyio >= 4.4.0, < 5.0
```

**Review by desertaxle — CHANGES_REQUESTED** [review]
I have one small final request, but after that, we should be good to cut a 2.x release!

**Comment by jnissin** [comment]
I updated the `anyio` upper limit to `<5.0.0` - let's see what the tests say 🤞
