### ISSUE TITLE
Variable flow names not working in Prefect>=2.19.3

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#13950]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using a variable as name for a flow results in `AttributeError: 'Name' object has no attribute 'value'` on deploy. This worked with Prefect <2.19.3

### Reproduction

```python3
from prefect import flow

NAME = "myflow"

@flow(name=NAME)
def main() -> None:
    pass
```

### Error

```bash
✗ prefect deploy test_flow.py:main 
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
  File ".venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File ".venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File ".venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File ".pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File ".venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File ".venv/lib/python3.10/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File ".venv/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/prefect/cli/deploy.py", line 479, in _run_single_deploy
    deploy_config["flow_name"] = load_flow_argument_from_entrypoint(
  File ".venv/lib/python3.10/site-packages/prefect/flows.py", line 1854, in load_flow_argument_from_entrypoint
    keyword.value.value
AttributeError: 'Name' object has no attribute 'value'
An exception occurred.
```

### Versions

```Text
Version:             2.19.4
API version:         0.8.4
Python version:      3.10.8
Git commit:          867543a8
Built:               Tue, Jun 4, 2024 3:14 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

When retrieving the name from a function `AttributeError: 'Call' object has no attribute 'value'
` is raised.

```
from prefect import flow

def flow_name():
    return "myflow"

@flow(name=flow_name())
def main() -> None:
    pass
```

**Comment by collincchoy** [comment]
closed by https://github.com/PrefectHQ/prefect/pull/13967
