### ISSUE TITLE
`SpacyNLP` task is not compatible with spacy >= 3.0

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#5358]
See CI failure at: https://app.circleci.com/pipelines/github/PrefectHQ/prefect/10850/workflows/1dabf16f-c1cb-4e02-9798-34e9ec12170a/jobs/140858

```
__________________ TestSpacyNLP.test_bad_model_raises_error ___________________
[gw1] linux -- Python 3.8.12 /usr/local/bin/python

self = <tests.tasks.spacy.test_spacy_tasks.TestSpacyNLP object at 0x7fc62cd96fa0>

    def test_bad_model_raises_error(self):
        with pytest.raises(ValueError, match="not_a_spacy_model"):
>           task = SpacyNLP(
                text="This is some text", spacy_model_name="not_a_spacy_model"
            )

tests/tasks/spacy/test_spacy_tasks.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/site-packages/prefect/core/task.py:159: in init
    old_init(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'SpacyNLP' object has no attribute 'name'") raised in repr()] SpacyNLP object at 0x7fc62cefd610>
text = 'This is some text', nlp = None, spacy_model_name = 'not_a_spacy_model'
disable = None, component_cfg = None, kwargs = {}

    def __init__(
        self,
        text: str = u"",
        nlp=None,
        spacy_model_name: str = "en_core_web_sm",
        disable: list = None,
        component_cfg: dict = None,
        **kwargs
    ):
        self.text = text
        self.disable = disable or []
        self.component_cfg = component_cfg or {}
    
        # load spacy model
        if nlp:
            self.nlp = nlp
        else:
            try:
>               self.nlp = spacy.load(
                    spacy_model_name,
                    disable=self.disable,
                    component_cfg=self.component_cfg,
                )
E               TypeError: load() got an unexpected keyword argument 'component_cfg'

/usr/local/lib/python3.8/site-packages/prefect/tasks/spacy/spacy_tasks.py:46: TypeError
```

`spacy` is pinned to `< 3.0` to prevent this from breaking builds, but ideally we would not have upper bound version constraints.

**Comment by makalaaneesh** [comment]
hi @madkinsz , can I pick this up? 

I can see from the [v3 docs](https://spacy.io/api/top-level#spacy.load) that the argument name is now `config` and not `component_cfg`. (Weird that it says it's a "new" argument in v3, because it seems like you could have done that in v2 with `component_cfg`). 

Couple of questions:
- I'm assuming we'd want to support both <3.0 and >3.0 for spacy, so prefect will have to have version-compatible code, correct? 
- An `exclude` param was also added to spacy's load method in v3 which is `Names of pipeline components to exclude. Excluded components won’t be loaded.`. Can I go ahead and add that to the args in the `SpacyNLP` task?

**Comment by madkinsz** [comment]
Hey @makalaaneesh, thanks for checking in!

@desertaxle can answer your questions. I think yes to both though.

**Comment by desertaxle** [comment]
Hey @makalaaneesh!

Thanks for volunteering to pick this up! We want to maintain backwards compatibility for users currently using this task, so will want the task to work with both <3.0 and >3.0 spacy. Adding a new param as long as it's not required is a backwards compatible change, so we should be able to support the `exclude` param. Looking forward to your PR!
