### ISSUE TITLE
The Flow diagram cannot be displayed when Prefect is deployed locally

### ISSUE THREAD

**Issue by Moonquakes** [PrefectHQ/prefect#17225]
### Bug summary

When trying to deploy locally by referring to the quick start document (https://docs.prefect.io/v3/get-started/quickstart), I cannot see the Flow image

![Image](https://github.com/user-attachments/assets/adcf3837-65f9-451b-8c27-e5fa711f0dd5)

### Version info

```Text
Version:             3.2.6
API version:         0.8.4
Python version:      3.10.13
Git commit:          5ceb3ada
Built:               Wed, Feb 19, 2025 9:24 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
```

**Comment by zzstoatzz** [comment]
hi @Moonquakes - thanks for the issue!

can you share your exact code? i am using the first flow from that quickstart you linked and seeing this against a server running locally

```
» prefect version
Version:             3.2.7
API version:         0.8.4
Python version:      3.12.7
Git commit:          a7e94adf
Built:               Fri, Feb 21, 2025 7:06 PM
OS/Arch:             darwin/arm64
Profile:             bleeding
Server type:         server
Pydantic version:    2.10.6
```

![Image](https://github.com/user-attachments/assets/9ffa8e27-5ace-4cf7-be80-386feb616a42)

**Comment by Moonquakes** [comment]
Hi @zzstoatzz, Thank you for your reply! I used the first code in the quickstart, the same as yours, and I saw this error on the browser: 

![Image](https://github.com/user-attachments/assets/57f0ec4f-4a00-485a-b54a-ef6a7302303c)

I had switched to an earlier version of Prefect and it seemed that I could see the images normally, but after I upgraded to the latest version, it no longer worked. I have not yet found the version that could display the images normally before.

**Comment by zzstoatzz** [comment]
hi @Moonquakes hrm are you able to record and share any server logs around the time of this failure? it looks like there's some server-side error at that time

**Comment by Moonquakes** [comment]
@zzstoatzz Here is the server-side error log:

                                                                                                                                                                                                     
```
16:00:58.896 | ERROR   | prefect.server - Encountered exception in request:                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1812, in _execute_context                                                                                  
    context = constructor(                                                                                                                                                                           
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1509, in _init_compiled                                                                                 
    d_param = {                                                                                                                                                                                      
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1511, in <dictcomp>                                                                                     
    flattened_processors[key](compiled_params[key])                                                                                                                                                  
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 2078, in process                                                                                          
    fixed_process_param(value, dialect)                                                                                                                                                              
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/database.py", line 162, in process_bind_param                                                                      
    if value.tzinfo is None:                                                                                                                                                                         
AttributeError: 'str' object has no attribute 'tzinfo'                                                                                                                                               
                                                                                                                                                                                                     
The above exception was the direct cause of the following exception:                                                                                                                                 
                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__                                                                                      
    await self.app(scope, receive, _send)                                                                                                                                                            
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__                                                                                         
    await responder(scope, receive, send)                                                                                                                                                            
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__                                                                                         
    await self.app(scope, receive, self.send_with_gzip)                                           
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__                                                                                   
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)                      
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app                                                                                   
    raise exc                                                                                                                                                                                          File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app                                                                                   
    await app(scope, receive, sender)                                                             
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__                                                                                                
    await self.middleware_stack(scope, receive, send)                                             
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app                                                                                                     
    await route.handle(scope, receive, send)                                                      
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle                                                                                                  
    await self.app(scope, receive, send)                                                                                                                                                             
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app                                                                                                      
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)                        
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app                                                                                   
    raise exc                                                                                     
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app                                                                                   
    await app(scope, receive, sender)                                                             
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 72, in app                                                                                                      
    response = await func(request)                                                                
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/server.py", line 50, in handle_response_scoped_depends                                                             
    response = await default_handler(request)                                                     
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app                                                                                                       
    raw_response = await run_endpoint_function(                                                                                                                                                      
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function                                                                                     
    return await dependant.call(**values)                                                                                                                                                            
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/api/flow_runs.py", line 342, in read_flow_run_graph_v2                                                                       
    return await read_flow_run_graph( 
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/models/flow_runs.py", line 610, in read_flow_run_graph                                                                       
    return await db.queries.flow_run_graph_v2(                                                                                                                                                       
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/database/query_components.py", line 507, in flow_run_graph_v2                                                                
    results = await session.execute(                                                                                                                                                                 
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 463, in execute                                                                                    
    result = await greenlet_spawn(                                                                                                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn                                                                          
    result = context.switch(*args, **kwargs)                                                                                                                                                         
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute                                                                                           
    return self._execute_internal(                                                                                                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal                                                                                 
    result: Result[Any] = compile_state_cls.orm_execute_statement(                                                                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement                                                                              
    result = conn.execute(                                                                                                                                                                           
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute                                                                                           
    return meth(                                                                                                                                                                                     
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection                                                                            
    return connection._execute_clauseelement(                                                                                                                                                        
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement                                                                            
    ret = self._execute_context(                                                                                                                                                                     
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1818, in _execute_context                                                                                  
    self._handle_dbapi_exception(                                                                                                                                                                    
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception                                                                           
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e                                                                                                                                    
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1812, in _execute_context                                                                                  
    context = constructor(                                                                        
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1509, in _init_compiled                                                                                 
    d_param = {                                                                                   
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1511, in <dictcomp>                                                                                     
    flattened_processors[key](compiled_params[key])                                                                                                                                                    File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 2078, in process                                                                                          
    fixed_process_param(value, dialect)                                                           
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/database.py", line 162, in process_bind_param                                                                      
    if value.tzinfo is None:                                                                      
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'tzinfo'                                                                                                      
[SQL: WITH edges AS                                                                               
(SELECT CASE WHEN (flow_run.id IS NOT NULL) THEN :param_1 ELSE :param_2 END AS kind, coalesce(flow_run.id, task_run.id) AS id, coalesce(flow.name || :name_1 || flow_run.name, task_run.name) AS labe
l, coalesce(flow_run.state_type, task_run.state_type) AS state_type, coalesce(flow_run.start_time, flow_run.expected_start_time, task_run.start_time, task_run.expected_start_time) AS start_time, co
alesce(flow_run.end_time, task_run.end_time, CASE WHEN (task_run.state_type = :state_type_1) THEN task_run.expected_start_time ELSE NULL END) AS end_time, JSON_EXTRACT(argument.value, :value_1) AS 
parent, input."key" = :key_1 AS has_encapsulating_task                                            
FROM task_run LEFT OUTER JOIN json_each(task_run.task_inputs) AS input ON 1 = 1 LEFT OUTER JOIN json_each(input.value) AS argument ON 1 = 1 LEFT OUTER JOIN flow_run ON flow_run.parent_task_run_id =
 task_run.id LEFT OUTER JOIN flow ON flow.id = flow_run.flow_id                                   
WHERE task_run.flow_run_id = :flow_run_id AND task_run.state_type != :state_type_2 AND coalesce(flow_run.start_time, flow_run.expected_start_time, task_run.start_time, task_run.expected_start_time)
 IS NOT NULL ORDER BY coalesce(flow_run.id, task_run.id)),                                        
with_parents AS                                                                                                                                                                                      
(SELECT children.id AS id, json_group_array(parents.id) AS parent_ids                             
FROM edges AS children JOIN edges AS parents ON parents.id = children.parent                                                                                                                         
WHERE children.has_encapsulating_task IS NOT 1 GROUP BY children.id),                             
with_children AS
(SELECT parents.id AS id, json_group_array(children.id) AS child_ids 
FROM edges AS parents JOIN edges AS children ON children.parent = parents.id 
WHERE children.has_encapsulating_task IS NOT 1 GROUP BY parents.id), 
with_encapsulating AS 
(SELECT children.id AS id, json_group_array(parents.id) AS encapsulating_ids 
FROM edges AS children JOIN edges AS parents ON parents.id = children.parent 
WHERE children.has_encapsulating_task IS 1 GROUP BY children.id), 
nodes AS 
(SELECT DISTINCT edges.kind AS kind, edges.id AS id, edges.label AS label, edges.state_type AS state_type, edges.start_time AS start_time, edges.end_time AS end_time, with_parents.parent_ids AS par
ent_ids, with_children.child_ids AS child_ids, with_encapsulating.encapsulating_ids AS encapsulating_ids
FROM edges LEFT OUTER JOIN with_parents ON with_parents.id = edges.id LEFT OUTER JOIN with_children ON with_children.id = edges.id LEFT OUTER JOIN with_encapsulating ON with_encapsulating.id = edge
s.id)
 SELECT nodes.kind, nodes.id, nodes.label, nodes.state_type, nodes.start_time, nodes.end_time, nodes.parent_ids AS parent_ids, nodes.child_ids AS child_ids, nodes.encapsulating_ids AS encapsulating
_ids
FROM nodes 
WHERE nodes.end_time IS NULL OR nodes.end_time >= :since ORDER BY nodes.start_time, nodes.end_time 
 LIMIT :max_nodes OFFSET :param_3]
[parameters: [{'flow_run_id': UUID('c25a39ed-8684-410b-bd86-d0a8bea77d2d'), 'since': '0001-01-01T00:00:00+00:00', 'max_nodes': 10001}]]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1812, in _execute_context
    context = constructor(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1509, in _init_compiled
    d_param = {
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1511, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 2078, in process
    fixed_process_param(value, dialect)
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/database.py", line 162, in process_bind_param
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/anaconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/api/server.py", line 153, in __call__
    await self.app(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/server.py", line 50, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/anaconda3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/api/flow_runs.py", line 342, in read_flow_run_graph_v2
    return await read_flow_run_graph(
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/models/flow_runs.py", line 610, in read_flow_run_graph
    return await db.queries.flow_run_graph_v2(
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/database/query_components.py", line 507, in flow_run_graph_v2
    results = await session.execute(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 463, in execute
    result = await greenlet_spawn(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1818, in _execute_context
    self._handle_dbapi_exception(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1812, in _execute_context
    context = constructor(
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1509, in _init_compiled
    d_param = {
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1511, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/anaconda3/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 2078, in process
    fixed_process_param(value, dialect)
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/database.py", line 162, in process_bind_param
    if value.tzinfo is None:
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'tzinfo'
[SQL: WITH edges AS 
(SELECT CASE WHEN (flow_run.id IS NOT NULL) THEN :param_1 ELSE :param_2 END AS kind, coalesce(flow_run.id, task_run.id) AS id, coalesce(flow.name || :name_1 || flow_run.name, task_run.name) AS labe
l, coalesce(flow_run.state_type, task_run.state_type) AS state_type, coalesce(flow_run.start_time, flow_run.expected_start_time, task_run.start_time, task_run.expected_start_time) AS start_time, co
alesce(flow_run.end_time, task_run.end_time, CASE WHEN (task_run.state_type = :state_type_1) THEN task_run.expected_start_time ELSE NULL END) AS end_time, JSON_EXTRACT(argument.value, :value_1) AS 
parent, input."key" = :key_1 AS has_encapsulating_task 
FROM task_run LEFT OUTER JOIN json_each(task_run.task_inputs) AS input ON 1 = 1 LEFT OUTER JOIN json_each(input.value) AS argument ON 1 = 1 LEFT OUTER JOIN flow_run ON flow_run.parent_task_run_id =
 task_run.id LEFT OUTER JOIN flow ON flow.id = flow_run.flow_id 
WHERE task_run.flow_run_id = :flow_run_id AND task_run.state_type != :state_type_2 AND coalesce(flow_run.start_time, flow_run.expected_start_time, task_run.start_time, task_run.expected_start_time)
 IS NOT NULL ORDER BY coalesce(flow_run.id, task_run.id)), 
with_parents AS 
(SELECT children.id AS id, json_group_array(parents.id) AS parent_ids 
FROM edges AS children JOIN edges AS parents ON parents.id = children.parent 
WHERE children.has_encapsulating_task IS NOT 1 GROUP BY children.id), 
with_children AS 
(SELECT parents.id AS id, json_group_array(children.id) AS child_ids 
FROM edges AS parents JOIN edges AS children ON children.parent = parents.id
WHERE children.has_encapsulating_task IS NOT 1 GROUP BY parents.id), 
with_encapsulating AS 
(SELECT children.id AS id, json_group_array(parents.id) AS encapsulating_ids 
FROM edges AS children JOIN edges AS parents ON parents.id = children.parent 
WHERE children.has_encapsulating_task IS 1 GROUP BY children.id), 
nodes AS 
(SELECT DISTINCT edges.kind AS kind, edges.id AS id, edges.label AS label, edges.state_type AS state_type, edges.start_time AS start_time, edges.end_time AS end_time, with_parents.parent_ids AS par
ent_ids, with_children.child_ids AS child_ids, with_encapsulating.encapsulating_ids AS encapsulating_ids 
FROM edges LEFT OUTER JOIN with_parents ON with_parents.id = edges.id LEFT OUTER JOIN with_children ON with_children.id = edges.id LEFT OUTER JOIN with_encapsulating ON with_encapsulating.id = edge
s.id)
 SELECT nodes.kind, nodes.id, nodes.label, nodes.state_type, nodes.start_time, nodes.end_time, nodes.parent_ids AS parent_ids, nodes.child_ids AS child_ids, nodes.encapsulating_ids AS encapsulating
_ids 
FROM nodes 
WHERE nodes.end_time IS NULL OR nodes.end_time >= :since ORDER BY nodes.start_time, nodes.end_time 
 LIMIT :max_nodes OFFSET :param_3]
[parameters: [{'flow_run_id': UUID('c25a39ed-8684-410b-bd86-d0a8bea77d2d'), 'since': '0001-01-01T00:00:00+00:00', 'max_nodes': 10001}]]
```

**Comment by zzstoatzz** [comment]
interesting, this looks like there was some trouble loading a datetime from the db

```python
  File "/home/anaconda3/lib/python3.10/site-packages/prefect/server/utilities/database.py", line 162, in process_bind_param                                                                      
    if value.tzinfo is None:                                                                                                                                                                         
AttributeError: 'str' object has no attribute 'tzinfo'     
```

**Comment by buyuk-dev** [comment]
Hi, thank you for resolving this - i've just run into this issue today and managed to fix it by switching to prefect==3.2.4 where this fix was released.

The thing is i've run into this issue initially on version 3.3.0 which seems to have been released today. I think something might have gone wrong with the new release that re-introduced this issue. Can someone take a look at it? @cicdw

**Comment by cicdw** [comment]
Hi @buyuk-dev - my MRE from when I fixed this is still working on the latest 3.3.0 release. If you could provide a reproducible example in a new issue I can look into it!

**Comment by buyuk-dev** [comment]
Hi @cicdw  sorry about long response times - i dont have the reproducible example and currently under deadline so cant spent time reproducing it. If i get a change i'll retest with a latest release to see if it still happens, but that probably has to wait a week or two. Currently running 3.2.14 which works for me. 3.3.0 was not.
