### PR TITLE
Resolve dbt profiles and other improvements

### LINKED ISSUE #18430: prefect-dbt - template rendering stopped working in 0.7.1
### Bug summary

During the release candidate for prefect dbt (0.7.0rc1) - template rendering as defined in the docs was working. 

However after upgrading to 0.7.1 - same flow no changes is erroring out with:

```
ValueError: Failed to invoke dbt command 'debug': Compilation Error
  Could not render {{ prefect.variables.target }}: 'prefect' is undefined
```

my profiles.yml looks similar to... :

```yaml
snowflake_dbt:
  target: "{{ prefect.variables.target }}" # complains about this on 0.7.1, fine in 0.7.0rc1
  outputs:
    dev:
      type: snowflake
      account: "{{ prefect.blocks.snowflake-credentials... }}"
      user: "{{ prefect.blocks.snowflake-credentials... }}"
      password: "{{ prefect.blocks.snowflake-credentials... }}"
      database: "{{ prefect.blocks.snowflake-connector... }}"
      schema: "{{ prefect.blocks.snowflake-connector...}}"
      warehouse: "{{ prefect.blocks.snowflake-connector... }}"
      threads: 12
```

Downgrade to the release candidate and I can run the flow.

flow code:

```python
from pathlib import Path

from prefect import flow, get_run_logger, task
from prefect_dbt import PrefectDbtRunner, PrefectDbtSettings
from prefect_github.repository import GitHubRepository
from pydantic import BaseModel, Field


class DbtConfig(BaseModel):
    """Represents a configuration for running dbt commands."""

    project_dir: str = Field(
        ...,
        description="The path to the dbt project directory.",
    )
    commands: list[str] = Field(
        ["debug"],
        description="The dbt commands to run. Defaults to ['debug']. Omit the dbt keyword.",
    )  


@task
def execute_dbt_command(
    settings: PrefectDbtSettings,
    command: str,
) -> None:
    logger = get_run_logger()
    logger.info(f"Executing dbt command: {command}")

    args = command.split(" ")
    PrefectDbtRunner(settings=settings).invoke(args=args)


@flow
def invoke_dbt(dbt_config: DbtConfig) -> None:
    """Invoke dbt commands for a given dbt project."""

    settings = PrefectDbtSettings(
        project_dir=Path(dbt_config.project_dir),
        profiles_dir=Path(dbt_config.project_dir) / ".prefect",
    )

    for command in dbt_config.commands:
        execute_dbt_command(settings, command)


if __name__ == "__main__":
    invoke_dbt(
        DbtConfig(
            project_dir="/path/to/dbt/project",
            commands=[
                "debug"
            ],
        )
    )
```

### Version info

```Text
Version:             3.4.7
API version:         0.8.4
Python version:      3.13.2
Git commit:          cd81d15a
Built:               Thu, Jun 26, 2025 09:16 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
Pydantic version:    2.11.7
Integrations:
  prefect-slack:     0.3.1
  prefect-dbt:       0.7.1
  prefect-github:    0.3.1
  prefect-snowflake: 0.28.5
  prefect-aws:       0.5.11
  prefect-shell:     0.3.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevingrismore**
Closes #18430

This PR makes a number of improvements and fixes to `prefect-dbt` intended for inclusion in `prefect-dbt==0.7.2`:
- Fixes resolution of templated Prefect blocks and Prefect variables in `profiles.yml`
- Fixes a logging race condition, ensuring all logs about a node are associated with their corresponding Prefect task run
- Prevents skipped nodes from getting task runs so skipped nodes don't give a false impression that they ran, and don't create or update assets. Includes children of nodes whose tests fail if using or retrying the `build` command

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [x] If this pull request adds functions or classes, it includes helpful docstrings.

### CODE REVIEW

File: src/integrations/prefect-dbt/tests/core/test_settings.py [hunk 1]
```diff
@@ -294,3 +294,207 @@ def test_settings_handle_complex_profiles_structure():
...
+                    )
+                elif isinstance(value, (dict, list)):
+                    resolved[key] = mock_resolve_blocks(value, value_transformer)
+                else:
+                    resolved[key] = value
+            return resolved
+        elif isinstance(data, list):
+            return [mock_resolve_blocks(item, value_transformer) for item in data]
+        else:
+            return data
```
Comment (zzstoatzz) [inline src/integrations/prefect-dbt/tests/core/test_settings.py]: why do we need this stuff?

**Review by zzstoatzz — COMMENTED** [review]
this generally LGTM, but i wonder if we need all the test code included in this PR

File: src/integrations/prefect-dbt/prefect_dbt/core/runner.py [hunk 2]
```diff
@@ -153,12 +167,27 @@ def manifest(self) -> Manifest:
...
         if self._project is None:
             self._set_project_from_project_dir()
             assert self._project is not None  # for type checking
         return self._project
 
+    @property
+    def graph(self) -> Graph:
+        if self._graph is None:
+            self._set_graph_from_manifest()
+            assert self._graph is not None  # for type checking
```
Comment (zzstoatzz) [inline src/integrations/prefect-dbt/prefect_dbt/core/runner.py]:
```suggestion
            assert self._graph is not None 
```

File: src/integrations/prefect-dbt/prefect_dbt/core/runner.py [hunk 3]
```diff
@@ -509,11 +578,28 @@ def invoke(self, args: list[str], **kwargs: Any):
         )
         task_state = NodeTaskTracker()
 
+        add_test_edges = True if "build" in args_copy else False
+
+        if "retry" in args_copy:
+            previous_results = load_result_state(
+                Path(self.project_dir) / self.target_path / "run_results.json"
```
Comment (zzstoatzz) [inline src/integrations/prefect-dbt/prefect_dbt/core/runner.py:585]: naive question: what's up with this hardcoded `run_results.json` path?

Comment (kevingrismore) [reply src/integrations/prefect-dbt/prefect_dbt/core/runner.py:585]: In dbt, [artifacts are written to a target directory](https://docs.getdbt.com/reference/artifacts/dbt-artifacts#where-are-artifacts-produced) relative to the configured project directory. This is `/target` by default but can be configured.

File: src/integrations/prefect-dbt/tests/core/test_settings.py (hunk 1 above)
Comment (kevingrismore) [reply src/integrations/prefect-dbt/tests/core/test_settings.py]: We definitely don't, I've still been struggling with making tests that are comprehensive but not repetitive. I'm considering starting from scratch because I'm not satisfied with how they're looking right now.

**Review by zzstoatzz — APPROVED** [review]
lgtm!
