### ISSUE TITLE
k8 agent doesn't cleanup after upgrading to 0.15.10. 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#5189]
## Description
After upgrading to 0.15.10 and enable `kubernetes_keep_alive` I start getting the following error message and the completed jobs don't get cleaned up. I might suspect it doesn't do the management of the jobs in general but I haven't confirmed this. I suspect it is related to #5066 as it started when upgrading from 0.15.7 to 0.15.10

```
[2021-12-02 15:45:36,640] ERROR - agent | Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
ERROR:agent:Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
[2021-12-02 15:46:38,459] ERROR - agent | Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
ERROR:agent:Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
[2021-12-02 15:47:40,119] ERROR - agent | Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
ERROR:agent:Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
ERROR:agent:Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
[2021-12-02 15:48:42,099] ERROR - agent | Error while managing existing k8s jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 406, in heartbeat
    self.manage_jobs()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 354, in manage_jobs
    and not self.client.get_flow_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1661, in get_flow_run_state
    return prefect.engine.state.State.deserialize(flow_run.serialized_state)
AttributeError: 'NoneType' object has no attribute 'serialized_state'
```

## Expected Behavior
No error and remove old jobs.

## Reproduction
Run k8 agent on Azure Kubernetes Servces.
Deploy agent with kubernetes_keep_alive configured.
Run Flow
Observe no deletion

## Environment
Runing on Azure Kubernetes Servces with agent using Docker image `prefecthq/prefect:0.15.10-python3.8`

**Comment by bnaul** [comment]
@thomasfrederikhoeck I was running into the same thing and it turned out to be related to authentication: specifically what @madkinsz pointed out [here](https://github.com/PrefectHQ/prefect/issues/5147#issuecomment-969270693) about mixing API keys and tokens. When I created new keys for everything issues resolved themselves.

**Comment by thomasfrederikhoeck** [comment]
@bnaul @madkinsz deleting old jobs, and switching to api keys solved it. Thank you.
