### ISSUE TITLE
prefect-dbt - template rendering stopped working in 0.7.1

### ISSUE THREAD

**Issue by steveh-101** [PrefectHQ/prefect#18430]
### Bug summary

During the release candidate for prefect dbt (0.7.0rc1) - template rendering as defined in the docs was working. 

However after upgrading to 0.7.1 - same flow no changes is erroring out with:

```
ValueError: Failed to invoke dbt command 'debug': Compilation Error
  Could not render {{ prefect.variables.target }}: 'prefect' is undefined
```

my profiles.yml looks similar to... :

```yaml
snowflake_dbt:
  target: "{{ prefect.variables.target }}" # complains about this on 0.7.1, fine in 0.7.0rc1
  outputs:
    dev:
      type: snowflake
      account: "{{ prefect.blocks.snowflake-credentials... }}"
      user: "{{ prefect.blocks.snowflake-credentials... }}"
      password: "{{ prefect.blocks.snowflake-credentials... }}"
      database: "{{ prefect.blocks.snowflake-connector... }}"
      schema: "{{ prefect.blocks.snowflake-connector...}}"
      warehouse: "{{ prefect.blocks.snowflake-connector... }}"
      threads: 12
```

Downgrade to the release candidate and I can run the flow.

flow code:

```python
from pathlib import Path

from prefect import flow, get_run_logger, task
from prefect_dbt import PrefectDbtRunner, PrefectDbtSettings
from prefect_github.repository import GitHubRepository
from pydantic import BaseModel, Field


class DbtConfig(BaseModel):
    """Represents a configuration for running dbt commands."""

    project_dir: str = Field(
        ...,
        description="The path to the dbt project directory.",
    )
    commands: list[str] = Field(
        ["debug"],
        description="The dbt commands to run. Defaults to ['debug']. Omit the dbt keyword.",
    )  


@task
def execute_dbt_command(
    settings: PrefectDbtSettings,
    command: str,
) -> None:
    logger = get_run_logger()
    logger.info(f"Executing dbt command: {command}")

    args = command.split(" ")
    PrefectDbtRunner(settings=settings).invoke(args=args)


@flow
def invoke_dbt(dbt_config: DbtConfig) -> None:
    """Invoke dbt commands for a given dbt project."""

    settings = PrefectDbtSettings(
        project_dir=Path(dbt_config.project_dir),
        profiles_dir=Path(dbt_config.project_dir) / ".prefect",
    )

    for command in dbt_config.commands:
        execute_dbt_command(settings, command)


if __name__ == "__main__":
    invoke_dbt(
        DbtConfig(
            project_dir="/path/to/dbt/project",
            commands=[
                "debug"
            ],
        )
    )
```

### Version info

```Text
Version:             3.4.7
API version:         0.8.4
Python version:      3.13.2
Git commit:          cd81d15a
Built:               Thu, Jun 26, 2025 09:16 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
Pydantic version:    2.11.7
Integrations:
  prefect-slack:     0.3.1
  prefect-dbt:       0.7.1
  prefect-github:    0.3.1
  prefect-snowflake: 0.28.5
  prefect-aws:       0.5.11
  prefect-shell:     0.3.1
```

**Comment by kevingrismore** [comment]
Sorry about that! #18410 fixes this and includes a number of other improvements. I expect it to be released today.
