### ISSUE TITLE
Mypy is reporting `incompatible type` for `flow` after upgrading to 3.1.6

### ISSUE THREAD

**Issue by dgarros** [PrefectHQ/prefect#16396]
### Bug summary

After upgrading to 3.1.6, mypy is reporting a lot of errors especially around `@flow` that are declared with `name` and `flow_run_name`
The issue is not present in 3.1.5 and it's not present if we remove `name` and `flow_run_name` from the `@flow` definition

Not sure if this is important but all our `@flow` are `async`

There are 2 types of errors
On the flow definition itself
```
backend/infrahub/computed_attribute/tasks.py:638: error: Argument 1 has
incompatible type "Callable[[str, str, str], Coroutine[Any, Any, None]]";
expected "Callable[[str, str, str], Never]"  [arg-type]
    @flow(
     ^
```

When we are calling the flow as a python function
```
backend/tests/integration/services/adapters/workflow/test_setup.py:14: error:
Incompatible types in "await" (actual type "None", expected type
"Awaitable[Any]")  [misc]
            await setup_task_manager()
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Here is how the flow definition looks like
```python
@flow(
    name="query-computed-attribute-transform-targets",
    flow_run_name="Query for potential targets of computed attributes for {node_kind}",
)
async def query_transform_targets(
```

### Version info

```Text
prefect version
Version:             3.1.6
API version:         0.8.4
Python version:      3.12.7
Git commit:          6bfce9e8
Built:               Wed, Dec 11, 2024 10:46 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.7.2
```

**Comment by zzstoatzz** [comment]
hi @dgarros - thank you for the issue! we've been making a lot of typing changes related to https://github.com/PrefectHQ/prefect/issues/16292. we'll take a look at this

**Comment by peku33** [comment]
Can confirm this in my project. Hundreds of typing errors after updating to 3.1.6.
- serve() won't accept async deployments
- @flow won't accept async functions
- asyncio.gather won't accept async (sub)flows
- won't accept awaiting async tasks

**Comment by dgarros** [comment]
@zzstoatzz I've checked with 3.1.12 and the issue with `@flow` has been resolved but I still have a similar error for `@task` ?
is it better to keep this one and update the title or to open a new issue ?

**Comment by dgarros** [comment]
Closing this one since the issue is not present for flow anymore
I've opened a new issue to track @task https://github.com/PrefectHQ/prefect/issues/16769
