### ISSUE TITLE
Starting a Prefect server with a very basic configuration does not work anymore

### ISSUE THREAD

**Issue by ubiquitousbyte** [PrefectHQ/prefect#16657]
### Bug summary

We are running Prefect v3.0.3 in production. I've been following the new releases very closely and wanted to upgrade to 3.1.11 today. Unfortunately, a very basic Prefect server configuration seems to not work anymore. This has something to do with the recent refactoring of the way Prefect deals with configuration settings - now these can be specified in toml files but they still need to be converted to environment variables for backwards compatibility and overall functionality preservation. 

The following server configuration does not work anymore:
```yaml
  prefect-database:
    image: postgres:15
    container_name: prefect-database
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    ports:
      - "5434:5432"
    volumes:
      - prefect-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:3.1.11-python3.12
    command: ["prefect", "server", "start"]
    container_name: prefect-server
    depends_on:
      prefect-database:
        condition: service_healthy
    ports:
      - "4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
      - PREFECT_UI_ENABLED=true
      - PREFECT_UI_STATIC_DIRECTORY=/ui_build
      - PREFECT_LOGGING_SERVER_LEVEL=DEBUG
      - PREFECT_API_DATABASE_DRIVER=postgresql+asyncpg
      - PREFECT_API_DATABASE_HOST=prefect-database
      - PREFECT_API_DATABASE_PORT=5432
      - PREFECT_API_DATABASE_NAME=prefect
      - PREFECT_API_DATABASE_USER=prefect
      - PREFECT_API_DATABASE_PASSWORD=prefect
```
You can ignore the database defintiion. It's the server that's failing when it tries to set up logging, which calls `to_environment_variables()` on `BaseSettings` which subsequently tries to dump the Pydantic model to a dictionary and that fails with the following trace:
```
prefect-server                 | Traceback (most recent call last):
prefect-server                 |   File "/usr/local/bin/prefect", line 5, in <module>
prefect-server                 |     from prefect.cli import app
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/cli/__init__.py", line 12, in <module>
prefect-server                 |     import prefect.cli.shell
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/cli/shell.py", line 16, in <module>
prefect-server                 |     from prefect import flow
prefect-server                 |   File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/__init__.py", line 113, in __getattr__
prefect-server                 |     module = importlib.import_module(mname, package=package)
prefect-server                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-server                 |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
prefect-server                 |     return _bootstrap._gcd_import(name[level:], package, level)
prefect-server                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/main.py", line 44, in <module>
prefect-server                 |     prefect.logging.configuration.setup_logging()
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/logging/configuration.py", line 71, in setup_logging
prefect-server                 |     config = load_logging_config(
prefect-server                 |              ^^^^^^^^^^^^^^^^^^^^
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/logging/configuration.py", line 41, in load_logging_config
prefect-server                 |     template.substitute(current_settings.to_environment_variables())
prefect-server                 |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/prefect/settings/base.py", line 92, in to_environment_variables
prefect-server                 |     env: Dict[str, Any] = self.model_dump(
prefect-server                 |                           ^^^^^^^^^^^^^^^^
prefect-server                 |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 426, in model_dump
prefect-server                 |     return self.__pydantic_serializer__.to_python(
prefect-server                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-server                 | pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `_serialize_secret_field`: AttributeError: 'str' object has no attribute 'get_secret_value'
```

### Version info

```Text
I am using the Docker image `prefecthq/prefect:3.1.11-python3.12`.
```

**Comment by desertaxle** [comment]
Thanks for the bug report @ubiquitousbyte! 

This error seems to be coming from the `PREFECT_API_DATABASE_DRIVER` et. al settings, but I'm not sure why yet. You can work around this by using `PREFECT_SERVER_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@prefect-database:5432/prefect` instead. I'll keep digging to see what the root cause for this error is.

**Comment by ubiquitousbyte** [comment]
Hey mate, yes that workaround works. Can the issue be in the `post_hoc_settings` [function](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/settings/models/root.py#L176)? I think it just needs some additional sanitisation, sth like 
```python
  db_pwd = (
      self.server.database.password.get_secret_value()
      if isinstance(self.server.database.connection_url, SecretStr)
      else self.server.database.password
  )  
```
before replacing it in `db_url`.

**Comment by desertaxle** [comment]
That's a great suggestion @ubiquitousbyte! I tried that out; it didn't work, but I did find the issue! Internally, we were accidentally setting `connection_url` to a plain string when the DB components were passed individually. I have a fix for it in https://github.com/PrefectHQ/prefect/pull/16680 if you want to give it a try!
