### PR TITLE
Convert strings to timezone-aware datetimes in the flow run graph API

### LINKED ISSUE #16487: graph-v2 requests fail after update to 3.1.9
When hitting: http://192.168.1.100:4200/api/flow_runs/c07e1f66-4187-48be-9b5d-5464aaaeddc2/graph-v2
It happens for all old and new flows, even those that were rendering fine in previous version (updated from 3.1.4)

```19:32:11.580 | ERROR   | prefect.server - Encountered exception in request:
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/prefect/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/home/user1/miniconda3/envs/prefect/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1493, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "/home/user1/miniconda3/envs/prefect/lib/python3.12/site-packages/sqlalchemy/sql/type_api.py", line 2037, in process
    fixed_process_param(value, dialect)
  File "/home/user1/miniconda3/envs/prefect/lib/python3.12/site-packages/prefect/server/utilities/database.py", line 127, in process_bind_param
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
```
image

```
Version:             3.1.9
API version:         0.8.4
Python version:      3.12.4
Git commit:          e1fe7943
Built:               Fri, Dec 20, 2024 4:33 PM
OS/Arch:             linux/x86_64
Profile:             user1
Server type:         server
Pydantic version:    2.8.2
```
_Originally posted by @kavvkon in https://github.com/PrefectHQ/prefect/issues/15153#issuecomment-2560078086_

### PR DESCRIPTION
**Pull request by cicdw**
I ran into this when trying to reproduce another issue - it seems like something changed in the UI that began sending naive strings instead of timezone-aware strings? Either way this makes the known problematic endpoint more robust to inputs.

Closes #16487
Closes https://github.com/PrefectHQ/prefect/issues/17225

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]
nice !
