### ISSUE TITLE
Mypy is reporting incompatible type for @task with arguments

### ISSUE THREAD

**Issue by dgarros** [PrefectHQ/prefect#16769]
### Bug summary

After upgrading to 3.1.13 from 3.0.11, mypy is reporting an `incompatible type` error for `@task` with some arguments defined at the decorator level (in my case the @task has `name` and `task_run_name` defined)

Without the arguments on the decorator, the error is not present.

```python
backend/infrahub/git/integrator.py:869: error: Argument 1 has incompatible type
"Callable[[InfrahubRepositoryIntegrator, str, Module, str, Any], Coroutine[Any, Any, list[TransformPythonInformation]]]";
expected
"Callable[[VarArg(Never), KwArg(Never)], Coroutine[Any, Any, list[TransformPythonInformation]]]"
 [arg-type]
        @task(name="python-transform-get", task_run_name="Get Python Trans...
         ^
```

### Version info

```Text
Version:             3.1.13
API version:         0.8.4
Python version:      3.12.7
Git commit:          16e85ce3
Built:               Fri, Jan 17, 2025 8:46 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.10.5
```

**Comment by zzstoatzz** [comment]
hi @dgarros - can you confirm that this issue persists on `main`? https://github.com/PrefectHQ/prefect/pull/16621 added an overload for the task decorator that fixed a very similar issue which has [not yet been released](https://github.com/PrefectHQ/prefect/compare/3.1.13..main)

```
uv pip install git+https://github.com/prefecthq/prefect.git
```

**Comment by dgarros** [comment]
@zzstoatzz I confirm the issue is fixed with the latest version in `main`, thank you
